[Desktop Entry]
Encoding=UTF-8
Name=Telepathy Send To
Name[cs]=Telepathy Odeslat na
Name[de]=Telepathy-Übertragung
Name[es]=Telepathy - Enviar a
Name[et]=Telepathy saatmine
Name[fi]=Telepathy – lähetä käyttäjälle
Name[fr]=Envoi via Telepathy
Name[hu]=Telepathy küldés ide
Name[it]=Invio via Telepathy
Name[km]=Telepathy ផ្ញើ​ទៅ
Name[lt]=Telepathy siuntimas
Name[mr]=टेलिपथी - यांना पाठवा
Name[nl]=Verzenden door Telepathy
Name[pl]=Wyślij do z Telepathy
Name[pt]=Envio do Telepathy
Name[pt_BR]=Enviar para do Telepathy
Name[ru]=Передача файлов с помощью Telepathy
Name[sk]=Telepathy poslať
Name[sv]=Telepathy skicka till
Name[tr]=Telepathy Şuraya Gönder
Name[uk]=Надсилання файлів за допомогою Telepathy
Name[x-test]=xxTelepathy Send Toxx
Comment=A tool to send images to IM contacts
Comment[cs]=Nástroj pro odesílání obrázků kontaktům komunikátoru
Comment[de]=Ein Werkzeug zum Senden von Bildern an Kontakte
Comment[es]=Una herramienta para enviar imágenes a contactos de MI (Mensajería Instantánea)
Comment[et]=Tööriist piltide saatmiseks kiirsuhtluskontaktidele
Comment[fi]=Työkalu, jonka avulla voi lähettää kuvia muille pikaviestinkäyttäjille
Comment[fr]=Un outil pour envoyer des images à des contacts de MI
Comment[ga]=Uirlis a sheolann íomhánna chuig teagmhálacha TM
Comment[gl]=Unha ferramenta para enviar imaxes a contactos da IM
Comment[hu]=Egy eszköz üzenetek küldéséhez IM partnereknek
Comment[it]=Uno strumento per inviare immagini a contatti di messaggistica istantanea
Comment[km]=ឧបករណ៍ ដើម្បី​ផ្ញើ​រូបភាព​ទៅ​ទំនាក់ទំនង IM
Comment[lt]=Įrankis siųsti paveikslėlius kontaktams
Comment[mr]=आयएम संपर्कांना प्रतिमा पाठविण्याचे साधन
Comment[nl]=Een hulpmiddel voor het verzenden van afbeeldingen naar IM-contactpersonen
Comment[pl]=Narzędzie do wysyłania obrazów do kontaktów z komunikatora internetowego
Comment[pt]=Uma ferramenta para enviar imagens para os contactos de MI
Comment[pt_BR]=Uma ferramenta para enviar imagens para contatos do IM
Comment[ru]=Инструмент для передачи изображений контактам сети обмена сообщениями
Comment[sk]=Nástroj na posielanie obrázkov pre IM kontakty
Comment[sv]=Ett verktyg för att skicka bilder till direktmeddelandekontakter
Comment[tr]=IM kişilerine resim göndermek için bir araç
Comment[uk]=Інструмент для надсилання зображень контактам мережі обміну повідомленнями
Comment[x-test]=xxA tool to send images to IM contactsxx
Type=Service
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_telepathy
Icon=telepathy-kde
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Daniele E. Domenichelli, daniele.domenichelli@gmail.com
